# Generated by Django 4.2.16 on 2024-11-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(help_text='Source language of the memory asset', max_length=50)),
                ('target_languages', models.TextField(help_text='Comma-separated target languages')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the memory asset was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the memory asset was last updated')),
            ],
            options={
                'db_table': 'memory_assets',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the memory', max_length=255)),
                ('source_language', models.CharField(help_text='Source language of the text', max_length=50)),
                ('target_language', models.CharField(help_text='Target language of the text', max_length=50)),
                ('source_text', models.TextField(help_text='Original text in the source language')),
                ('target_text', models.TextField(help_text='Translated text in the target language')),
                ('memory_asset', models.ForeignKey(help_text='The memory asset to which this memory belongs', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='ocr_service.memoryasset')),
            ],
            options={
                'db_table': 'translation_memory',
            },
        ),
    ]
