# Generated by Django 4.2.16 on 2024-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_service', '0002_memoryasset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryasset',
            name='name',
            field=models.CharField(default='', help_text='Name of the memory asset', max_length=100),
        ),
    ]
